// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoResizeController from "./auto_resize_controller.ts"
application.register("auto-resize", AutoResizeController)

import AutosubmittingController from "./autosubmitting_controller.ts"
application.register("autosubmitting", AutosubmittingController)

import CalendarController from "./calendar_controller.ts"
application.register("calendar", CalendarController)
