import '@hotwired/turbo';
import { Application } from '@hotwired/stimulus';
import { start } from '@nerdgeschoss/shimmer';
import SidebarController from '../../components/sidebar/sidebar_controller';
import ButtonController from '../../components/button/button_controller';

const application = Application.start();
application.register('sidebar', SidebarController);
application.register('button', ButtonController);
start({ application });

import '../components/reset.scss';
import '../../components/stack/stack.scss';
import '../../components/logo/logo.scss';
import '../../components/container/container.scss';
import '../../components/card/card.scss';
import '../../components/text/text.scss';
import '../../components/form_error/form_error.scss';
import '../../components/text_field/text_field.scss';
import '../../components/button/button.scss';
import '../../components/icon/icon.scss';
import '../../components/avatar/avatar.scss';
import '../../components/tooltip/tooltip.scss';
import '../../components/sidebar/sidebar.scss';
import '../../components/layout/layout.scss';
import '../../components/property/property.scss';
import '../../components/pill/pill.scss';
import '../../components/modal/modal.scss';
import '../../components/performance_grid/performance_grid.scss';
import '../../components/performance/performance.scss';
import '../../components/performance_progress/performance_progress.scss';
import '../../components/performance_days/performance_days.scss';
import '../../components/employee_card/employee_card.scss';
import '../../components/divider/divider.scss';
import '../../components/icon_title/icon_title.scss';
import '../../components/performance_labels/performance_labels.scss';
import '../../components/star_display/star_display.scss';
import '../../components/text_box/text_box.scss';
import '../../components/status_pill/status_pill.scss';
import '../../components/performance_day/performance_day.scss';
import '../../components/select_field/select_field.scss';
import '../../components/columns/columns.scss';
import '../../components/text_area/text_area.scss';
