AllCops:
  SuggestExtensions: false

inherit_gem:
  shimmer: config/rubocop_base.yml

# TODO: Move this to Shimmer
Naming/MemoizedInstanceVariableName:
  Enabled: true

RSpec/ExpectChange:
  Enabled: true
  EnforcedStyle: block
