# frozen_string_literal: true

source "https://rubygems.org"
ruby "~> #{File.read(File.join(__dir__, "../.ruby-version")).strip}"

# Specify your gem's dependencies in translate_client.gemspec
gemspec

gem "rake", "~> 13.0"

group :test, :development do
  gem "rspec"
  gem "webmock"
end
