# frozen_string_literal: true

module Types
  class ProjectContributorType < Types::BaseObject
    description "One user's contribution to a project within a profit month (hours, revenue, allocated cost)."

    field :id, ID, null: false,
      description: "Globally unique identifier scoped to the parent project row."
    field :user, Types::UserType, null: false,
      description: "User whose hours produced this slice."
    field :hours, Float, null: false,
      description: "Billable hours the user logged on this project this month."
    field :revenue, Float, null: false,
      description: "Revenue generated by this user on this project this month, in EUR."
    field :cost, Float, null: false,
      description: "Slice of the user's monthly cost allocated to this project (proportional to hours)."
  end
end
