version: '3'

services:
  app:
    image: ghcr.io/nerdgeschoss/nerdgeschoss/development-environment:3.3-22
    volumes:
      - ../..:/workspaces:cached
      - nerdgeschoss_app-node_modules:/workspaces/nerdgeschoss_app/node_modules
      - ~/.netrc:/root/.netrc
      - ~/.ssh:/root/.ssh
      - ~/.config/gh:/root/.config/gh
      - ~/.aws:/root/.aws

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    environment:
      TZ: Europe/Berlin

  db:
    image: postgres:15.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres-data:
  nerdgeschoss_app-node_modules:
