:concurrency: 3
:queues:
  - dispatch
  - default
  - mailers
  - import
  - notification
:schedule:
  harvest_import:
    every: '30m'
    class: HarvestImportJob
  slack_notification:
    cron: '0 8 * * * Europe/Berlin' # every day at 8:00, Berlin time
    class: SlackNotificationJob

