:concurrency: 3
:queues:
  - dispatch
  - default
  - mailers
  - import
  - notification
:scheduler:
  :schedule:
    harvest_import:
      every: "30m"
      class: HarvestImportJob
    github_import:
      every: "30m"
      class: GithubImportJob
    slack_notification:
      cron: "0 8 * * * Europe/Berlin" # every day at 8:00, Berlin time
      class: SlackNotificationJob
    slack_congratulation:
      cron: "0 9 * * * Europe/Berlin" # every day at 9:00, Berlin time
      class: SlackCongratulationJob
    slack_status:
      cron: "0 0 * * * Europe/Berlin" # every day at 00:00, Berlin time
      class: SlackSetStatusJob
