default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        harvest_import_job:
          class: HarvestImportJob
          schedule: "*/30 * * * *" # every 30 minutes
        github_import_job:
          class: GithubImportJob
          schedule: "*/30 * * * *" # every 30 minutes
        slack_notification_job:
          class: SlackNotificationJob
          schedule: "0 8 * * * Europe/Berlin" # every day at 8:00, Berlin time
        slack_congratulation_job:
          class: MyJob
          schedule: "0 9 * * * Europe/Berlin" # every day at 9:00, Berlin time
        slack_set_status_job:
          class: MyJob
          schedule: "0 0 * * * Europe/Berlin" # every day at 00:00, Berlin time
  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
