name: CI

on: [push]

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  RAILS_ENV: test
  DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/app
  RSPEC_RETRY_RETRY_COUNT: 3
  SCREENSHOTS: '1'

jobs:
  ruby:
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies from apt
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips42
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: yarn
      - name: Install yarn
        run: yarn install
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Lint
        run: bundle exec rubocop
      - name: Check Model Annotations
        run: bundle exec annotaterb models --frozen
      - name: JS Lint
        run: yarn lint
      - name: Install Playwright Browsers
        run: npx --yes playwright install --with-deps chromium
      - name: Build
        run: bundle exec rails assets:precompile
      - name: Create PG Database
        run: bundle exec rake db:create db:migrate
      - name: Build and test with RSpec
        run: bundle exec rspec --format documentation
